services:
  postgres:
    image: 'postgres:14-alpine'
    restart: always
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=skyvern
      - POSTGRES_PASSWORD=skyvern
      - POSTGRES_DB=skyvern
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U skyvern'
      interval: 5s
      timeout: 5s
      retries: 5
  skyvern:
    image: 'public.ecr.aws/skyvern/skyvern:latest'
    restart: on-failure
    volumes:
      - './artifacts:/data/artifacts'
      - './videos:/data/videos'
      - './har:/data/har'
      - './log:/data/log'
      - './.streamlit:/app/.streamlit'
    environment:
      - 'DATABASE_STRING=postgresql+psycopg://skyvern:skyvern@postgres:5432/skyvern'
      - BROWSER_TYPE=chromium-headful
      - ENABLE_CODE_BLOCK=true
      - VITE_ENABLE_CODE_BLOCK=true
      - 'LLM_KEY=${LLM_KEY:-}'
      - 'SECONDARY_LLM_KEY=${SECONDARY_LLM_KEY:-}'
      - 'GEMINI_API_KEY=${GEMINI_API_KEY:-}'
      - 'ENABLE_GEMINI=${ENABLE_GEMINI:-false}'
      - 'CORS_ORIGIN=${CORS_ORIGIN:-*}'
      - 'SKYVERN_API_KEY=${SKYVERN_API_KEY:?}'
      - 'BITWARDEN_SERVER=http://bitwarden-cli'
      - BITWARDEN_SERVER_PORT=8087
      - 'SKYVERN_AUTH_BITWARDEN_ORGANIZATION_ID=${SKYVERN_AUTH_BITWARDEN_ORGANIZATION_ID}'
      - 'SKYVERN_AUTH_BITWARDEN_CLIENT_ID=${SKYVERN_AUTH_BITWARDEN_CLIENT_ID:?}'
      - 'SKYVERN_AUTH_BITWARDEN_CLIENT_SECRET=${SKYVERN_AUTH_BITWARDEN_CLIENT_SECRET:?}'
      - 'SKYVERN_AUTH_BITWARDEN_MASTER_PASSWORD=${SKYVERN_AUTH_BITWARDEN_MASTER_PASSWORD:?}'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - test
        - '-f'
        - /app/.streamlit/secrets.toml
      interval: 5s
      timeout: 5s
      retries: 5
  skyvern-ui:
    image: 'public.ecr.aws/skyvern/skyvern-ui:latest'
    restart: on-failure
    volumes:
      - './artifacts:/data/artifacts'
      - './videos:/data/videos'
      - './har:/data/har'
      - './.streamlit:/app/.streamlit'
    environment:
      - 'VITE_API_BASE_URL=${VITE_API_BASE_URL:?}'
      - 'VITE_WSS_BASE_URL=${VITE_WSS_BASE_URL:?}'
      - 'VITE_ARTIFACT_API_BASE_URL=${VITE_ARTIFACT_API_BASE_URL:?}'
      - 'VITE_ENVIRONMENT=${VITE_ENVIRONMENT:-production}'
      - 'VITE_SKYVERN_API_KEY=${VITE_SKYVERN_API_KEY:?}'
    depends_on:
      skyvern:
        condition: service_healthy
  vaultwarden:
    image: 'vaultwarden/server:latest-alpine'
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: 'https://vaultwarden.points.place'
      SIGNUPS_ALLOWED: 'false'
    volumes:
      - '~/vw-data/:/data/'
  bitwarden-cli:
    image: 'ghcr.io/olsonbd/bitwarden-cli:latest'
    restart: unless-stopped
    environment:
      - 'BW_HOST=http://vaultwarden'
      - 'BW_CLIENTID=${BW_CLIENTID:?}'
      - 'BW_CLIENTSECRET=${BW_CLIENTSECRET:?}'
      - 'BW_PASSWORD=${BW_PASSWORD:?}'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8087/status'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      vaultwarden:
        condition: service_healthy
    volumes:
      - '~/bitwarden-cli-config:/app/.config'
    labels:
      - traefik.enable=false
